openapi: 3.1.0
info:
  version: 1.0.0
  title: <назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    contact app project
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
    url: https://contacts-app-s1ab.onrender.co
paths:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer